version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: mysql:5
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cakephp_blog_db
      MYSQL_ROOT_PASSWORD: cakephp
    ports:
    - "3306:3306"

volumes:
  db-data:
    external: false